language: go
jobs:
  include:
    - go: 1.15
os: linux
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libhwloc-dev libnuma-dev
install:
  - go build ./...
script: true
after_script:
  - go test -race -v -cover ./...
